### ISSUE TITLE
Discord->IRC stops working after a while, IRC->Discord sill working

### ISSUE THREAD

**Issue by lrabe** [reactiflux/discord-irc#25] opened 2016-01-05 11:27 UTC
Hi, 

while the relay works right after installation and a specific period of time afterwards (worked for at least 30 minutes, didn't measure time exactly), at some point message sent from Discord won't appear in in the IRC channel anymore.
The other way around still works, however

Example video: http://gfycat.com/OffensiveTalkativeFiddlercrab

The terminal doesn't show any errors (besides a "nosuchchannel" error that comes from the "mode test +x" command right after joining, but I doubt that's related since everything works at first).

Channel permissions for the bot should be fine.

My config: 

```js
[
 // Bot 2 (advanced options):
  {
    "nickname": "discordion",
    "server": "irc.rizon.net",
    "discordEmail": "removed@redacted.nope",
    "discordPassword": "123",
    "autoSendCommands": [ // Commands that will be sent on connect
      ["PRIVMSG", "NickServ", "IDENTIFY 123"],
      ["MODE", "test", "+x"]
      // ["AUTH", "test", "password"]
    ],
    "channelMapping": { // Maps each Discord-channel to an IRC-channel, used to$
      "#irc-relaychan": "#vurelaytest" // Add channel keys after the chan$
    },
    "ircOptions": { // Optional node-irc options
      "floodProtection": true, // On by default
      "floodProtectionDelay": 500 // 500 by default
    },
    // Makes the bot hide the username prefix for messages that start
    // with one of these characters (commands):
    "commandCharacters": ["!"]
  }
]
```

**Comment by tusing** [comment] 2016-01-12 19:47
Can confirm - I am having the same issue. Started after around 3 days on my VPS.

**Comment by ekmartin** [comment] 2016-01-23 19:42
discord-irc 0.4.3 uses a more up to date version of discord.js which might be worth testing. If you export the environment variable `NODE_ENV` to `development` before running discord-irc you'll also get some more log output, which might help investigate the issue.

**Comment by ekmartin** [comment] 2016-04-04 10:58
Closing this as I believe it might have been fixed by upgrading to discord.js 6.1.0 (which is used by discord-irc 0.6.1). Feel free to let me know if the issue still persists, and I'll reopen.

**Comment by alienth** [comment] 2016-04-21 01:30
I believe this may need to be reopened. I'm experiencing this on the latest discord.js, and latest discord-irc (0.8.0). Seems to be happening very frequently last few days. I suspect discord API itself may be triggering this condition.

**Comment by ekmartin** [comment] 2016-04-21 01:37
Thank you for the heads up - I'll try to investigate further.

**Comment by alienth** [comment] 2016-04-21 02:07
I'm doing a connection via discord.js alongside my normal bot. Logging all message / warning / notice stuff. Will letcha know if I see anything.

**Comment by ekmartin** [comment] 2016-04-21 02:48
Found out that discord.js had an `autoReconnect` option now, so I've enabled that and published it in version 0.8.2 of discord-irc. 0.8.2 also upgrades discord.js to the latest version (6 -> 7). 

It looks like there might be a few issues with `autoReconnect` though (https://github.com/hydrabolt/discord.js/issues/276) - but it's worth a try.

**Comment by alienth** [comment] 2016-04-21 02:56
I doubt it is a reconnection scenario, as one direction of communication continues to work. That is, Discord still sees the IRC messages.

**Comment by ekmartin** [comment] 2016-04-21 03:16
From a quick look at discord.js it looks it posts using HTTP to [send messages](https://github.com/hydrabolt/discord.js/blob/master/src%2FClient%2FInternalClient.js#L634), and only uses WebSockets for [receiving](https://github.com/hydrabolt/discord.js/blob/master/src%2FClient%2FInternalClient.js#L1474-L1485). So sending would probably still work if the WS connection was down?

**Comment by alienth** [comment] 2016-04-21 03:18
Mm, perhaps. I'll see if I'm getting a `disconnected` event.

**Comment by ajwhite** [comment] 2016-04-21 03:22
Experiencing the same - IRC -> Discord is fine, but not the other way around.

I notice that `discord.on('message', ..)` **does** receive the message.

**Comment by ajwhite** [comment] 2016-04-21 03:25
Whoops - I lied, this was because I was testing with the bot user in the discord channel.

**Comment by alienth** [comment] 2016-04-21 21:00
Confirmed in my case it is due to disconnects, which reconnect fixes. I think this can be closed.

**Comment by ekmartin** [comment] 2016-04-21 21:06
Sounds good, thanks for investigating!

**Closed by ekmartin** 2016-04-21 21:06 UTC
