### ISSUE TITLE
unhandled message

### ISSUE THREAD

**Issue by Stanzilla** [reactiflux/discord-irc#306] opened 2017-09-24 12:56 UTC
```
24 Sep 14:55:18 - Unhandled message: { prefix: 'rajaniemi.freenode.net',
  server: 'rajaniemi.freenode.net',
  command: '378',
  rawCommand: '378',
  commandType: 'normal',
  args:
   [ 'WoWUIDevDiscord',
     'WoWUIDevDiscord',
     'is connecting from *@X' ] }

```

**Comment by Throne3d** [comment] 2017-09-25 03:26
This is a duplicate of #304.

**Closed by Throne3d** 2017-09-25 03:26 UTC
Labels: upstream bug
