### ISSUE TITLE
Unicode character problem

### ISSUE THREAD

**Issue by SombraRO** [reactiflux/discord-irc#399] opened 2018-05-12 02:55 UTC
Every message that uses the character `ç` next to another Unicode returns a strange character.

**Using encode: UTF-8**

`çã `Shows how `згo`
`çõ` Shows how `уш`

This is problem with the **Iconv-lite**

This can only be reproduced if the message is sent from irc to discord irc can not be UTF-8

**Comment by SombraRO** [comment] 2018-05-12 02:56
@Throne3d  and @ekmartin  Can you confirm?

**Comment by Throne3d** [comment] 2018-05-12 15:34
Looks to be reproducible. If I install mIRC, and disable the "UTF-8 encode/decode messages" option, and then send `çõ` and `çã`, it reproduces. (`ça` and `ço` do not, so it presumably needs to be a non-ASCII character following the `ç`.)

I would expect this _not_ to be a problem with iconv-lite, though, but instead with jschardet, as it's presumably when it's trying to figure out what the encoding of the string is instead of when it's actually performing the change to the string encoding. <https://github.com/ashtuchkin/iconv-lite/issues/187> should probably be closed, in favor of opening an issue over at <https://github.com/aadsm/jschardet/issues>.

**Comment by SombraRO** [comment] 2018-05-12 15:50
@Throne3d Before when I was using iconv and node-icu-charset-detector worked well, after the update that was sent yesterday it started to occur problem.

**Comment by Throne3d** [comment] 2018-05-12 15:51
@SombraRO Yep, I would expect that. It updated to use iconv-lite and jschardet. iconv-lite only converts between two known encodings, whereas jschardet is the place that tries to figure out what encoding the original message is in. It's more likely that jschardet is simply guessing wrong than that iconv-lite is converting between known encodings incorrectly, I expect.

**Comment by SombraRO** [comment] 2018-05-12 15:53
Thank you I will wait for a confirmation of **jschardet** .

**Comment by SombraRO** [comment] 2018-05-12 20:03
@Throne3d If jschardet doesn't give an answer any possibility to change the dependency?

I was looking on github and I found the chardet

https://github.com/runk/node-chardet

**Comment by Mikaela** [comment] 2018-05-13 11:07
I started seeing this or something similar after updating to https://github.com/reactiflux/discord-irc/releases/tag/v2.6.1 but I am and my users are using UTF-8.

For example when I say `Kyllä` (Yes in Finnish) at IRC, it comes to Discord as `KyllĂ¤`. And in longer strings of text, the ä/ö start turning into Chinese or Japanese characters randomly, but not always. 

Someone following this said that this is a result of double-UTF-8 even if I am not sure what that means.

**Comment by redfellow** [comment] 2018-05-16 21:48
I too started experiencing this today after I switching from commit of discord-irc from this repository to the npm package. All `ä` and `ö` characters from IRC display as `Ă¤` in Discord. I've got the fresh webhook functionality enabled as well.

**Comment by JoinedSenses** [comment] 2018-05-24 21:52
I recieve this problem as well and it causes some issues, since I use a game server plugin that relays messages containing UTF-8 chars to an IRC channel.

**Comment by Mikaela** [comment] 2018-05-30 07:10
I managed to workaround this by adding `"encoding": null` into `"ircOptions": { }`, as I don't need charset recording, because everyone is either using UTF-8 or that is not my problem.

Thanks to:
* getting enough annoyed by having a bad day and one user accidentally hitting that button
* https://github.com/martynsmith/node-irc/issues/327#issuecomment-74918037 *It is for an optional feature for converting a server's encoding from UTF-8 to something else.*
* https://github.com/aadsm/jschardet/issues/47 for talking about random charsets
* https://node-irc-upd.readthedocs.io/en/latest/API.html#irc.Client and README for pointing me to there.

**Comment by Throne3d** [comment] 2018-05-30 16:44
It looks like swapping to jschardet was a mistake. I'll look into https://github.com/runk/node-chardet, as @SombraRO suggested, over the next few weeks, and if that doesn't fix it I'll revert to using ICU. (I figure that it's better for it to work properly with the right dependencies, and fail otherwise, than for it to fail weirdly across the board.)

**Comment by Throne3d** [comment] 2018-06-02 01:06
Alright, I should have the issue fixed in the upstream repository. I'd like to check if it works in practice, before trying to get another release out with it in, and so I've updated a fork of discord-irc to use this updated version, over at <https://github.com/Throne3d/discord-irc>. If someone could try using that version of discord-irc (likely by checking out the repository from source), and reporting whether it resolves the issue, I'd appreciate it – otherwise, I'll probably cut a new release of the upstream library within a week, and then discord-irc should update to that soon afterwards.

**Comment by awunder** [comment] 2018-08-28 18:20
but only for a few hours.. kept it running but after a while it stopped working.. IRC special characters were back "screwed" on the discord side

**Comment by tenleftfingers** [comment] 2018-09-25 19:43
I'm currently experiencing this issue with accented characters á, é, í, ó and ú which show up as a, e, i, o and u in Discord. Latest version of discord-irc is 2.6.1 at time of writing which we are running.

Is the version at https://github.com/Throne3d/discord-irc newer or older than this reactiflux version? I'm happy to test whichever needs testing.

**Comment by JoinedSenses** [comment] 2018-09-27 00:17
If you dont use any sort of special encoding, one of the above comments solved my problem

https://github.com/reactiflux/discord-irc/issues/399#issuecomment-393054180

**Comment by Throne3d** [comment] 2018-10-08 22:38
@tenleftfingers Sorry to take so long to get back on this. The version as of you writing _should_ have actually been 2.6.2 - and is in the code on master branch, we just didn't add a new tag or release for it. This version (reactiflux, 2.6.2) should currently be more up to date.

Do you still have trouble if you use 2.6.2?

**Comment by tenleftfingers** [comment] 2018-10-16 17:32
@Throne3d I used Mikaela's workaround with 2.6.1 to solve this issue https://github.com/reactiflux/discord-irc/issues/399#issuecomment-393054180

(Sorry too, for my delay!)

**Comment by Throne3d** [comment] 2019-08-04 23:38
Closing this as it should be fixed in recent versions of discord-irc.

**Closed by Throne3d** 2019-08-04 23:38 UTC
Labels: upstream bug
