### ISSUE TITLE
Suggested Options

### ISSUE THREAD

**Issue by dwhagar** [reactiflux/discord-irc#133] opened 2016-10-07 15:48 UTC
I would really like to see options to allow someone to see who is online on IRC / Discord from the other side of the bridge.  So, if someone on IRC types like !names it'll give a list of whose on Discord and vise versa, if someone on Discord uses the same command it'll say whose on IRC.

If I knew more node.js / javascript, I'd program it myself, but I don't unfortunately.

**Comment by ekmartin** [comment] 2016-10-07 15:49
Duplicate of https://github.com/reactiflux/discord-irc/issues/92

**Closed by ekmartin** 2016-10-07 15:49 UTC
