### ISSUE TITLE
I don't know how github works so posting this here

### ISSUE THREAD

**Issue by jamesguessis** [reactiflux/discord-irc#164] opened 2016-11-28 04:10 UTC
But if you're the only person using the bridge on the discord side of things, is there a way to remove the username when sending the message in irc?

**Comment by ekmartin** [comment] 2016-11-28 05:01
Not configurable, but if you pull down the code/fork the repository, the correct line to edit would be https://github.com/reactiflux/discord-irc/blob/master/lib/bot.js#L165 (just remove the whole line). For attachments you'd have to remove [this line](https://github.com/reactiflux/discord-irc/blob/master/lib/bot.js#L172) and use `a.url` directly instead of `urlMessage`.

Closing this as it's a duplicate of #13.

**Closed by ekmartin** 2016-11-28 05:01 UTC
