### ISSUE TITLE
Bot often reconnects to IRC and stops working when it receives ERR_NOTREGISTERED (QuakeNet)

### ISSUE THREAD

**Issue by Bleidd64** [reactiflux/discord-irc#504] opened 2019-08-12 11:23 UTC
Bot connects to Discord and IRC, relays messages, but after some time it reconnects to IRC, after some more time it disconnects from IRC (EOF from client) and in the logs it says following thing:
```
2019-08-12T11:01:54.187Z error: Received error event from IRC {
  prefix: 'euroserv.fr.quakenet.org',
  server: 'euroserv.fr.quakenet.org',
  command: 'err_notregistered',
  rawCommand: '451',
  commandType: 'error',
  args: [ 'dbot', 'dbot', 'Register first.' ],
  level: undefined,
  message: undefined,
  timestamp: '2019-08-12T11:01:54.187Z',
  splat: undefined,
  [Symbol(level)]: 'error',
  [Symbol(splat)]: [
    {
      prefix: 'euroserv.fr.quakenet.org',
      server: 'euroserv.fr.quakenet.org',
      command: 'err_notregistered',
      rawCommand: '451',
      commandType: 'error',
      args: [ 'dbot', 'dbot', 'Register first.' ]
    }
  ]
}
```
Config is as follows:
```
[
  {
    "nickname": "dbot",
    "server": "euroserv.fr.quakenet.org",
    "discordToken": "REDACTED",
    "autoSendCommands": [
      ["AUTH", "dbot", "REDACTED"]
    ],
    "channelMapping": {
      "#server-chat": "#jeff-xonotic"
    },
    "ircOptions": {
      "encoding": null
    }
  }
]
```

**Comment by Throne3d** [comment] 2019-08-12 13:05
Could you enable debug mode, by putting `"debug" : true` into `ircOptions` and starting the bot with the environment variable `NODE_ENV=development`? I'm not clear on why the authentication would work some times but not others, and hopefully the logs will show what went on in the auth process to cause this. (Note that your logs will get very verbose, and you may need to redact passwords or tokens from the auth process. The auth process should contain the line `AUTH dbot redacted`, possibly with some colons between words.)

**Comment by Bleidd64** [comment] 2019-08-12 13:19
I enabled debug mode and I am currently waiting for it to stop working, it takes some time

**Comment by Bleidd64** [comment] 2019-08-12 13:48
[log.txt](https://github.com/reactiflux/discord-irc/files/3492746/log.txt)

**Comment by Throne3d** [comment] 2019-08-12 15:32
I'm not sure what's causing the underlying disconnections – the ping that the bot sends to the server isn't being responded to, so we get a timeout. (The very first line of the log shows that we do get `PONG` responses _sometimes_, but they stopped after that line and never resumed.) The reason the bot then doesn't _continue_ to reconnect, after the ten reconnections, is that we've hit the automatic retry cap (this defaults to 10 in discord-irc). The log you just uploaded here doesn't contain `err_notregistered`, so that makes me think that that specific error in the original issue text was a fluke and is unlikely to repeat.

You could ensure the bot will keep reconnecting by adding `"retryCount": null` to your `ircOptions` object in the configuration (so it will retry an unlimited amount). This might help if the issue is just down to a few minutes of spotty network connection, though it will probably still disconnect and reconnect as frequently as it has been doing. Maybe try that? In the meantime, I'll see if I can reproduce the issue when I connect to quakenet.

**Comment by Bleidd64** [comment] 2019-08-12 15:54
It shouldn't be any network issues, because there is another IRC bot run on same machine, connecting to euroserv.fr.quakenet.org too and it doesn't have any issues. Anyway I ran it with retryCount null to see if it helps. If it doesn't I might as well write a patch which restarts the bot when it disconnects, because that solves the issue temporaily

**Comment by Throne3d** [comment] 2019-08-12 16:03
Well, I just managed to get disconnected from euroserv.fr.quakenet.org both with my bot and with my actual IRC client, so I'm gonna say that it's very likely an issue with the server. Maybe your other IRC bot is just really permissive about ping timeouts? Have you tried using a different server to connect to quakenet?

**Comment by Bleidd64** [comment] 2019-08-12 16:06
Or maybe other bot is set up for other quakenet than euroserv.fr (wasn't me setting it up), I'll change it and let you know

**Comment by Throne3d** [comment] 2019-12-14 17:15
I'll close this for now – I assume that since there hasn't been any follow-up, it was a problem with the IRC server as suspected.

If this is still happening, feel free to get back! =)

**Closed by Throne3d** 2019-12-14 17:15 UTC
Labels: needs info
