### ISSUE TITLE
Feature request: Convert *actions* into IRC /me actions

### ISSUE THREAD

**Issue by dustwolf** [reactiflux/discord-irc#331] opened 2017-10-28 10:32 UTC
It would be appreciated if it were possible -- perhaps as a configurable option, for discord-irc to automatically convert statements which have \*star actions from start to finish\* into /me actions.

> `PRIVMSG #channel :\001ACTION message`

**Comment by Throne3d** [comment] 2017-10-28 12:48
This is a duplicate of #143, so I'm closing it in favor of that.

There were some problems with figuring out how to implement this feature. For one – CTCP actions are often displayed by clients with the bot's name at the start. We could just send it as an action message directly, in which case something like this would happen:

```
<BridgeBot> <Throne3d> Hey there!
* BridgeBot waves
```

when really what we want is for it to somehow show that Throne3d is (I am) waving – it's ambiguous who's doing it, because it could have been someone else waving in response to me.

We could just append the username? But then you get something like this:

```
<BridgeBot> <Throne3d> Hey there!
* BridgeBot Throne3d waves
```

That looks weird, in my opinion, and would probably confuse me.

Alternatively, we could just send it as a regular message but format it differently:

```
<BridgeBot> <Throne3d> Hey there!
<BridgeBot> Throne3d waves
```

This seems (to me) like it's probably the best of the options, and it should be a configurable format, but I'm not actually sure if you could configure it from this to be a CTCP action. (Probably, if you can just insert `\001ACTION ` at the start of the custom format, and I think end it with `\001`.)

The main other problem I can see would be detecting a message as an action. Discord literally sends actions (e.g. `/me waves`) with underscores wrapped around them (e.g. `_waves_`), though this looks identical to with asterisks. We'd need to make sure the whole message is covered in the italics, with no breaks at any point, and that it's actually parsed as italics. We can probably do this with `simple-markdown`, which we use at the moment to parse markdown and convert it to IRC formatting.

(Responses should go on the other issue, #143, to consolidate this all.)

**Closed by Throne3d** 2017-10-28 12:48 UTC
