### ISSUE TITLE
Different Discord Channels mapped to the same IRC channel breaks one of the relays

### ISSUE THREAD

**Issue by doublehelix457** [reactiflux/discord-irc#579] opened 2021-01-17 04:48 UTC
In my config, i have two separate guild channels, mapped to the same IRC channel. It appears that the latter channel in the mapping list works fine, but the second one fails to send IRC -> discord.

**Comment by Throne3d** [comment] 2021-04-24 04:12
Hi there! We don't support 1:n mappings between IRC and Discord channels, and as the project is in maintenance mode, it's unlikely we'll implement it soon – closing as a duplicate of #459.

**Closed by Throne3d** 2021-04-24 04:12 UTC
