### ISSUE TITLE
Bridge seems to ignore nick-changes by webhook-bots

### ISSUE THREAD

**Issue by TildeSlashC0re** [reactiflux/discord-irc#393] opened 2018-04-30 09:09 UTC
As is the bot seems to only acknowledge the first name picked up from other webhook-users (bots) inside the chats and will work with those. 

Currently I am bridging a telegram room <> matrix room <> discord channel <> irc

So I have two webhooks inside the discord channel (one for the discord<>irc bridge and one for matrix<>discord bridge) and the IRC side reflects only the first name of the matrix<>discord webhook  which doesn't really help in identifying who send what on the other network as the chat progresses.

**Comment by Throne3d** [comment] 2019-08-04 23:36
Is this still a problem? As I understand it, this used to be a restriction in the past, but I've tried to reproduce it just now and I can't seem to, so it looks like it's fixed.

**Comment by Throne3d** [comment] 2020-08-09 02:44
Closing due to a lack of more recent info! If this is still a problem (especially after the upcoming upgrade to discord.js), please get back in contact =)

**Closed by Throne3d** 2020-08-09 02:44 UTC
Labels: needs info
