### ISSUE TITLE
Discord role appears as "@deleted-role" on IRC

### ISSUE THREAD

**Issue by Kovaelin** [reactiflux/discord-irc#364] opened 2018-02-11 20:08 UTC
When messaging a custom role on Discord, it appears as "@deleted-role" on IRC. I'm not sure, but could this be caused by roles that have spaces in the names? It appears normally for "@here" or "@everyone".

**Comment by Throne3d** [comment] 2018-02-15 22:13
What's the name of the role? It could be broken by a space, but I think that'd be a weird result of the current code. Can you make a one-word role and try pinging that, then checking what appears for that?

**Comment by Kovaelin** [comment] 2018-02-16 01:58
It's definitely caused by the space. I made other roles with and without spaces, to check. Pinging the one-word roles appears normally.

**Comment by Throne3d** [comment] 2018-04-20 23:03
I'm not able to reproduce it with some roles I just created, `@new role` and `@another role`. Do you know if there's something else special about your setup? Has it been fixed in a recent version of `discord-irc`?

**Comment by Kovaelin** [comment] 2018-04-24 02:46
Seems to be fixed after the most recent version.

**Comment by Throne3d** [comment] 2018-04-24 02:48
No problem! I'm still not sure what was up with it, so it might recur – for now, I'll close the issue, but if you find it happening again, just comment here.

**Closed by Throne3d** 2018-04-24 02:48 UTC
Labels: bug, needs info

**Comment by Kovaelin** [comment] 2018-05-03 18:57
It's been about a month now, and it hasn't happened again. So far; so good. I'm not sure what else it might have been. The only other special thing I can think of would be the capitalization in ```@The Role```. The role also had the same name as one of the Discord channel categories and channels themselves. I've since changed the name of the category. I have no idea if that would have been related, and that particular channel was not using the bridge.

Anyway, it seems to have been sorted out, so thanks again for looking into it.

**Comment by Throne3d** [comment] 2018-05-04 12:30
I'm glad that it's fixed! :)

I don't see why any of those things would have broken it, but maybe I'll stumble upon something eventually.

**Comment by slovene** [comment] 2018-05-25 14:16
well, using the role id of @everyone and pinging using it (<@&214026475203067904> ) outputs @deleted-role.
so either the fix has been deleted or it wasn't good enough.
