### ISSUE TITLE
IRC bot disconnects on QUIT but not on PART

### ISSUE THREAD

**Issue by Broken-R3D** [reactiflux/discord-irc#226] opened 2017-04-27 11:50 UTC
Hello, to be honest,  i made this git account just to post this..

i get the error when someone quits in irc chat-room as `Cannot read property 'delete' of undefined` but it isn't happening on part.. i tried changing code as in the previous issues but wasn't successful. So as a safety measure, i tried part/quit to false in config and works well.. but since i get Realname@xxx.xxx.xxx.xx.IP quit on debug log, can't we just use that to post in discord, same with part and join too.. Honestly i don't know the code so it would have been better if you do that for me(and someone else)

Regards,

**Comment by Throne3d** [comment] 2017-04-27 12:19
Pretty sure this is a duplicate of #216, which was fixed in #219 but does not appear to have been released yet.

I'm going to guess the channel the bot is connected to is not in lowercase?

The hostname part of the message does not clearly identify the username that has left the channel unless one also receives this hostname when said user joined or by some other method, so I do not think using that would help this problem?

The issue is that the library we are using to interface with IRC sends the quit event with all channels the bot is connected to, instead of just the channels the user left from; I attempted to get around this by listing the channels each user was in and then restricting the messages just to the ones the user quit from, but I failed to take into account that the IRC library does not lowercase channel names consistently which caused the issue.

**Comment by ekmartin** [comment] 2017-04-27 12:20
I'll publish a release in a few hours - sorry.

**Comment by Throne3d** [comment] 2017-04-27 12:20
@ekmartin Ping that there doesn't seem to be a release of that fix yet.

**Comment by Broken-R3D** [comment] 2017-04-27 12:44
thanks @Throne3d and @ekmartin ... chan is lowercase and all info is correct.. no offence but really thankyou for answer :+1:

**Comment by ekmartin** [comment] 2017-04-27 13:51
I published version 2.3.2 with @Throne3d's fixes - could you see give it a try and see if it still crashes?

**Comment by Throne3d** [comment] 2017-04-27 14:40
If it doesn't work, and you're *sure* you updated appropriately, could you please paste console debug here? That message doesn't help me out a ton.

Also useful would be the server you're using (IP and port) and the name of the channel, so I can try to reproduce it myself.

**Comment by Broken-R3D** [comment] 2017-04-28 22:09
@Throne3d @ekmartin Sorry to be late but the problem is still there
Server: Rizon
port: 6667
channel: #17

**Comment by Throne3d** [comment] 2017-04-28 22:23
I just tried reproducing it and on Rizon in that channel I was able to join, part and quit without it crashing…

**Comment by Broken-R3D** [comment] 2017-04-29 19:32
@Throne3d Got two configs one for real and one for test.. the test works but the real one doesnt, any idea why ?

Real config: `{"nickname":"Nickname","server":"ircserver","discordToken":"TOKEN","autoSendCommands":[["PRIVMSG","NickServ","IDENTIFY pass"],["MODE","Nickname","+x"]],"channelMapping":{"285467517642866698":"#india.suna","306487320285282305":"#sec.india","306897136480550912":"#kpp99","306897685322137600":"#h20","306902216659304448":"#bridge","306488307754336267":"#17"},"ircOptions":{"floodProtection":false,"floodProtectionDelay":1000,"debug":true},"format":{"commandPrelude":"Command sent by {$nickname}","ircText":"<{$displayUsername}> {$text}","urlAttachment":"<{$displayUsername}> {$attachmentURL}","discord":"**<{$author}>** {$withMentions}"},"ircNickColor":true,"commandCharacters":["!"],"ircStatusNotices":true}
`

Test config: `{"nickname":"Nickname","server":"Server","discordToken":"TOKEN","autoSendCommands":[["PRIVMSG","NickServ","IDENTIFY pass"],["MODE","Nickname","+x"]],"channelMapping":{"306510507291049986":"#17"},"ircOptions":{"floodProtection":false,"floodProtectionDelay":1000,"debug":true},"format":{"commandPrelude":"Command sent by {$nickname}","ircText":"<{$displayUsername}> {$text}","urlAttachment":"<{$displayUsername}> {$attachmentURL}","discord":"**<{$author}>** {$withMentions}"},"ircNickColor":true,"commandCharacters":["!"],"ircStatusNotices":true}
`
i don't know what wrong. the bot just quits for real config and not the other one :(

**Comment by Throne3d** [comment] 2017-04-29 20:34
The only thing that looks different between them is the list of channels – I thought it could be that some channels have `.` in them, but that doesn't seem to break it for me.

Could you run the bot with the `NODE_ENV` environment variable set to `development`? If you're on Linux and using Bash, `NODE_ENV=development npm start -- --config conf.json` should do this – if you can copy the bits towards the end (anywhere near it saying `Received quit`, preferably a bit before, make sure you redact any passwords) including the full error message, that might be useful.

**Comment by Broken-R3D** [comment] 2017-04-29 20:59
@Throne3d 
`debug: Sending special message to Discord *LoveLord* has joined the channel #17 -> #red
debug: Sending special message to Discord *LoveLord* has left the channel (undefined) #17 -> #red
debug: Sending special message to Discord *LoveLord* has joined the channel #17 -> #red
29 Apr 20:57:01 - QUIT: LoveLord!~ReDevil@7D83CFE2.1807BB28.1D90CF7F.IP
/usr/local/lib/node_modules/discord-irc/node_modules/irc/lib/irc.js:849
                        throw err;
                        ^

TypeError: Cannot read property 'delete' of undefined
    at channels.forEach.channel (/usr/local/lib/node_modules/discord-irc/dist/bot.js:173:40)
    at Array.forEach (native)
    at Client.ircClient.on (/usr/local/lib/node_modules/discord-irc/dist/bot.js:172:16)
    at emitMany (events.js:127:13)
    at Client.emit (events.js:204:7)
    at Client.<anonymous> (/usr/local/lib/node_modules/discord-irc/node_modules/irc/lib/irc.js:595:22)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:191:7)
    at iterator (/usr/local/lib/node_modules/discord-irc/node_modules/irc/lib/irc.js:846:26)
    at Array.forEach (native)
`
i don't usually use npm start so instead i used `NODE_ENV=development discord-irc --config configtwo.json` donnow if it changes anything.. but i pasted the log above

**Comment by Throne3d** [comment] 2017-04-29 22:54
If you know how, could you try checking out #218 and retrying this, seeing if you get more in the way of helpful errors? (It shouldn't in fact crash if you use #218 but there's likely a different problem I should look into solving, which #218 will help with.)

**Comment by ekmartin** [comment] 2017-04-30 02:15
Published #218 in version 2.3.3 - feel free to give it a try.

**Comment by Broken-R3D** [comment] 2017-04-30 05:58
@Throne3d @ekmartin I tried #218 but error still is there

`debug: Sending special message to Discord *LoveLord* has joined the channel #17 -> #red
debug: Sending special message to Discord *LoveLord* has left the channel (undefined) #17 -> #red
debug: Sending special message to Discord *LoveLord* has joined the channel #17 -> #red
30 Apr 05:56:53 - QUIT: LoveLord!~ReDevil@xxxxxxxxxxxxxxxxxxxxxxxxxxx.IP
/usr/local/lib/node_modules/discord-irc/node_modules/irc/lib/irc.js:849
                        throw err;
                        ^

TypeError: Cannot read property 'delete' of undefined
    at channels.forEach.channel (/usr/local/lib/node_modules/discord-irc/dist/bot.js:173:40)
    at Array.forEach (native)
    at Client.ircClient.on (/usr/local/lib/node_modules/discord-irc/dist/bot.js:172:16)
    at emitMany (events.js:127:13)
    at Client.emit (events.js:204:7)
    at Client.<anonymous> (/usr/local/lib/node_modules/discord-irc/node_modules/irc/lib/irc.js:595:22)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:191:7)
    at iterator (/usr/local/lib/node_modules/discord-irc/node_modules/irc/lib/irc.js:846:26)
    at Array.forEach (native)
`

**Comment by ekmartin** [comment] 2017-04-30 06:17
Hm, are you sure you correctly installed the new version? Try `npm uninstall -g discord-irc`, then `npm install -g discord-irc` again. 

The reason I'm asking is because `/usr/local/lib/node_modules/discord-irc/dist/bot.js:173` says the `.delete()` call is on line 173, but comparing to my own local version of the distributed `bot.js` it should be 172.

**Comment by Broken-R3D** [comment] 2017-04-30 12:38
@ekmartin  Thanks bro <3 it worked ! also, if I could, i want to use https://github.com/rlidwka/node-hotswap .. can you tell me where to put config files of hotswap ?

Regards,
Love ya

**Comment by Throne3d** [comment] 2017-04-30 12:50
… I don't expect hotswapping the config would do anything as the bot copies the data internally. Also I don't think this project uses 'hotswap' anywhere?

Is your problem actually completely fixed or are there still warning messages showing?

**Comment by Broken-R3D** [comment] 2017-04-30 12:56
@Throne3d Ah no more error... its all completely fixed.. what i was asking is, can i hotswap the process ? in anyway possible

**Comment by Throne3d** [comment] 2017-04-30 13:01
Not to my knowledge. There's another bug asking about that, #191.

**Closed by Throne3d** 2017-04-30 13:01 UTC

**Comment by Broken-R3D** [comment] 2017-04-30 13:05
Thanks guys <3
