### ISSUE TITLE
wants bot join channel automatically on adding new entries to config.json

### ISSUE THREAD

**Issue by Broken-R3D** [reactiflux/discord-irc#228] opened 2017-05-01 09:35 UTC
Hello,

It would have been nice if bot join automatically to new irc channels when added a new entry to config.json file while the process is running.

Regards,

**Comment by Throne3d** [comment] 2017-07-03 21:46
This seems to basically be a duplicate of #191, in that if we enable functionality to hot-swap channels, you could automate this yourself.

**Closed by Throne3d** 2017-07-03 21:46 UTC
