### ISSUE TITLE
Bot suddenly stops sending messages to IRC

### ISSUE THREAD

**Issue by ask-compu** [reactiflux/discord-irc#167] opened 2016-12-09 03:47 UTC
the bot randomly stops sending messages to discord to IRC but still sends them from IRC to discord, restarting the bot fixes this temporarily but only for a day or 2, constantly restarting the bot is getting irritating, especially since my users have to tell me when this is happening as the bot's terminal output gives no indication of problems

**Comment by ekmartin** [comment] 2016-12-09 04:07
Duplicate of #159.

**Closed by ekmartin** 2016-12-09 04:07 UTC
