### ISSUE TITLE
Bot goes offline and stops relaying Discord to IRC (one-way)

### ISSUE THREAD

**Issue by StrikerMan780** [reactiflux/discord-irc#326] opened 2017-10-13 03:16 UTC
For some reason, the bot eventually goes offline, and still somewhat works, as in it'll relay chat from IRC to Discord, but it won't relay the other way.

Here's a screenshot to show what I mean:
![screenshot](https://i.imgur.com/gnsf5oa.png)

The IRC chat is working, but if I type something in Discord, the IRC channel never receives it. I'm using the latest version of Discord-IRC.

**Comment by MuffinMedic** [comment] 2017-10-14 15:17
I've been having this issue as well. Bot stays online for both services, but the relay only seems to go IRC -> Discord.

**Comment by 10thTARDIS** [comment] 2017-10-14 19:46
+1

I've been having this issue too.  It was a lot worse when it was hosted on my DigitalOcean droplet, and it's more stable now that it's hosted on my homelab, but it still does happen.

**Comment by Throne3d** [comment] 2017-10-15 01:40
I noticed this problem the other day. When I debugged it, I got some stuff including:

```
debug: Received debug event from Discord [ws] [connection] Connected to gateway wss://gateway.discord.gg/?v=6&encodi
ng=json
debug: Received debug event from Discord [ws] [connection] Identifying as a new session
debug: Received debug event from Discord [ws] [connection] Server closed the WebSocket connection: 1000
debug: Received debug event from Discord [ws] [connection] Attemping to reconnect in 5500ms...
```

After asking in the Discord API server in the `discord.js` channel about what error 1000 meant, I was told it indicates the connection cut off completely (that the websocket shut down with no valid error). This should happen with regular connection loss, though, which it doesn't always seem to. Somehow it only disconnects partially (?), which is weird. `discord.js` apparently does not try to reconnect when it receives this error, even [when told to automatically reconnect](https://github.com/reactiflux/discord-irc/blob/db39ba237eb68ae521a43d0134c3e33fe5317c82/lib/bot.js#L28) (and apparently `autoReconnect` isn't a thing anymore; it's now always true).

`discord.js` provides a `disconnect` event on the client, so we could bind to that and have it reconnect then, which may solve this problem. If I get some time I'll look into submitting a PR for it and maybe see if I can more consistently figure out when it happens. I think this used to be a bigger problem also before the `node-irc` library was forked and updated, since I used to notice it a lot more frequently in the past but haven't since making changes to that.

**Comment by doublehelix457** [comment] 2017-10-18 15:10
Ive been having the same issue, only discord messages send, but the bot doesnt recieve messages from the IRC channels. I keep it running with the debug and show errors options on but it just doesnt show messages sending, no errors. I usually have it screened for days at a time and after a few days I have to restart the bot. (Around the 11,000ish ping). I am up to date.

**Comment by Throne3d** [comment] 2017-10-21 23:22
Hm. When I tried to make it happen manually, it acted differently from the logs someone gave me – I ended up getting a repeated heartbeat sent but no response, even once I reconnected my internet connection, but it (as expected) sent messages from IRC to Discord and not vice versa. The bot also showed as offline.

I can't seem to find anything in the upstream `discord.js` which allows me to check for a heartbeat timing out – in fact, as far as I can tell they never check for whether it _has_ timed out, they just check when they get a response to figure out ping times? For now this looks like an upstream bug though I haven't submitted a report of the issue or anything.

To reproduce: there's a gist [here](https://gist.github.com/Throne3d/d064994be4282a320e9026c5db087cf7) which constructs a `discord.js` client setup (using the token from a conf.json file, though you can modify the top few lines to hardcode it instead). If you disconnect your internet while it's running, wait for a heartbeat, then reconnect it, it seems to send messages when told to (type `message('string')` into the REPL) but doesn't emit for any message events on the connected server. It also doesn't acknowledge a response to any heartbeats, and the bot shows up as offline on an attached server. After about fifteen minutes it seems to get a 1006 error and reconnects properly.

**Comment by rnyberg** [comment] 2017-12-04 09:19
Also affected on this, bot connected to two networks, other network randomly stops relaying from Discord to IRC after few days of bot running just fine.

**Comment by redfellow** [comment] 2018-05-21 12:06
This still requires daily restarts of the bot (running in a DigitalOcean droplet).

**Comment by Kovaelin** [comment] 2018-05-30 19:57
This happened last week while Discord was having problems. The bot went down and never reconnected. Discord messages could not be sent to IRC, but IRC messages kept being relayed to Discord.

I think I've seen it happen the other way around too.

**Comment by redfellow** [comment] 2018-05-30 20:06
I worked around this problem by setting a chron job to re-launch the bot every 12 hours (Ubuntu 14.04). In case someone needs help setting this up, here's how I did it (suboptimal, but works)

* make a folder for the scripts and then:
* run command: `nano run.sh`
* paste into the file, and save (replace paths as needed):
```
#!/bin/sh
discord-irc --config /home/red/discord-irc/config.json
```
* run command: `chmod +x run.sh`
* run command: `nano discord-irc.sh`
```
#!/bin/sh
ps -ef | grep discord-irc-bridge | grep -v "grep" | awk '{print $2}' | xargs kill;
/usr/bin/screen -dmS discord-irc-bridge sh /home/red/discord-irc/run.sh
```
* run command: `chmod +x discord-irc.sh`
* run command: `crontab -e`
* paste to the bottom:
```
@reboot sleep 8 && sh /home/red/discord/discord-irc.sh
0 */12 * * * sh /home/red/discord/discord-irc.sh
```

**Comment by Throne3d** [comment] 2020-08-09 02:57
I haven't noticed this problem recently, so I'll close this issue as possibly fixed. Please get back in touch if you notice any recent connectivity issues!

**Closed by Throne3d** 2020-08-09 02:57 UTC
Labels: bug, needs info, upstream bug

**Comment by DominusExult** [comment] 2022-09-01 21:48
I ran into this today :(
It worked fine three hours ago but now it won't relay from Discord to IRC even after restarting the docker. IRC to Discord works

**Comment by SprainedSpark89** [comment] 2023-01-06 01:49
i have the same issue but it doesn't go offline and if you ping it it will work for that message
