### ISSUE TITLE
bummer

### ISSUE THREAD

**Issue by AeSix** [reactiflux/discord-irc#62] opened 2016-04-28 15:02 UTC
Looks like there are serious issues with this code and nodejs 4.4.3 - as in it wont' install. 
Maybe it's nodejs. Maybe it's gyp. Maybe it's npm. Maybe it's ubuntu 15.10. I don't know.
All I know is at 8am, I started working to get this installed. It's now 11. I'm done.

Maybe you can look into the issue so that you're not losing additional future prospective users as well.

**Comment by ekmartin** [comment] 2016-04-28 16:16
Kind of hard to look into the issue without an error log, mind posting one?

**Comment by ekmartin** [comment] 2016-04-30 10:37
Closing this for now, can't reproduce using Node 4 and Ubuntu 15.10.

**Closed by ekmartin** 2016-04-30 10:37 UTC
