### ISSUE TITLE
Error with bot.js:118

### ISSUE THREAD

**Issue by rappo** [reactiflux/discord-irc#484] opened 2019-04-21 04:11 UTC
I've installed discord-irc using npm as instructed in the readme. I set up a very basic config using the example (see mine below) and launched discord-irc via 
> discord-irc --config discord-irc.json

I get the error below. Any suggestions on how I can resolve this?

(Apologies if this isn't the best place to get support, I went to reactiflux discord and no one there seemed to be familiar with the project.)

```
:~$ discord-irc --config discord-irc.json
/usr/local/lib/node_modules/discord-irc/dist/bot.js:118
      const [id, token] = url.split('/').slice(-2);
            ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/discord-irc/dist/helpers.js:12:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

my config is very basic:
```
[
  {
    "nickname": "irc-discord",
    "server": "irc.freenode.net",
    "discordToken": "REDACTED",
    "channelMapping": {
      "channel-ID-here": "##ircchannelhere"
    }
  }
]
```

**Comment by Kovaelin** [comment] 2019-06-02 04:40
Have you tried `#ircchannelhere` without that second `#` in your config?

**Comment by Throne3d** [comment] 2019-08-04 21:45
The issue looks like you might be on an old version of Node, because it's not recognizing a piece of modern syntax. What version are you using?

**Comment by loopyd** [comment] 2019-08-11 14:23
Getting the same error message here on an openshift container instance:

	SyntaxError: lib/bot.js: Unexpected token (118:6)
	  116 |       autoRenick: true,
	  117 |       // options specified in the configuration file override the above defaults
	> 118 |       ...this.ircOptions
		  |       ^
	  119 |     };
	  120 | 
	  121 |     // default encoding to UTF-8 so messages to Discord aren't corrupted
	npm info lifecycle discord-irc@2.7.2~build: Failed to exec build script
	npm ERR! code ELIFECYCLE
	npm ERR! errno 1
	npm ERR! discord-irc@2.7.2 build: `babel lib --out-dir dist`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the discord-irc@2.7.2 build script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
	npm timing npm Completed in 650ms

My JSON checks out just fine with JSONLint.  npm version 10

    npm info using node@v10.13.0

**Comment by Throne3d** [comment] 2019-08-11 17:13
@loopyd I tried installing node@v10.13.0, and then used `npm install -g discord-irc`, and it succeeded for me just fine. What command did you use to install `discord-irc`? Also, what version of npm are you using? (You can find out with `npm --version`.)

**Comment by loopyd** [comment] 2019-08-12 00:13
@Throne3d are you building from source, or installing the version from npm ?

I'm building it from source.  Still trouble shooting, I think its a babel problem.  Unexpected tokens all over the place.

**Comment by Throne3d** [comment] 2019-08-12 01:10
With respect to my last comment, when I tried to reproduce your issue, I was installing the version from npm.

I've now tried reproducing the issue on the source code, as well, with node@v10.13.0, and couldn't. The following commands succeeded for me, and included a transpilation of the files in `lib/` to `dist/`:

```
 ~/Repos $ nvm use v10
Now using node v10.13.0 (npm v6.4.1)
 ~/Repos $ git clone git@github.com:reactiflux/discord-irc.git
Cloning into 'discord-irc'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 2494 (delta 17), reused 14 (delta 10), pack-reused 2458
Receiving objects: 100% (2494/2494), 844.73 KiB | 1.40 MiB/s, done.
Resolving deltas: 100% (1681/1681), done.
 ~/Repos $ cd discord-irc
 ~/Repos/discord-irc  master $ node --version
v10.13.0
 ~/Repos/discord-irc  master $ npm --version
6.4.1
 ~/Repos/discord-irc  master $ npm install

> discord-irc@2.7.2 prepare /mnt/c/Users/thron/Repos/discord-irc
> npm run build


> discord-irc@2.7.2 build /mnt/c/Users/thron/Repos/discord-irc
> babel lib --out-dir dist

lib/bot.js -> dist/bot.js
lib/cli.js -> dist/cli.js
lib/errors.js -> dist/errors.js
lib/formatting.js -> dist/formatting.js
lib/helpers.js -> dist/helpers.js
lib/index.js -> dist/index.js
lib/logger.js -> dist/logger.js
lib/validators.js -> dist/validators.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 585 packages from 1116 contributors and audited 2947 packages in 33.83s
 ~/Repos/discord-irc  master $ ls dist
bot.js  cli.js  errors.js  formatting.js  helpers.js  index.js  logger.js  validators.js
```

(Note that this includes the build step `babel lib --out-dir dist`, which works on my device.)

1. What version of npm are you using?
2. Did you use `npm install` to produce the issue, on the latest master commit (221d42a44bef3bb6fafaded46b880c2bf78f1aea), or something else?
3. Do you have a local version of `babel` that it might be using (`which babel`)?

**Comment by loopyd** [comment] 2019-08-12 02:09
1.  npm info using npm@6.4.1
2. I was able to get babel running via config.json, here is the actual code which runs in my .s2i/bin/assemble:

```
	echo "---> Installing all dependencies"
	NODE_ENV=development npm install

	#do not fail when there is no build script
	echo "---> Building in production mode"
	npm run build --if-present

	echo "---> Pruning the development dependencies"
	npm prune

	# Clear the npm's cache and tmp directories only if they are not a docker volumes
	NPM_CACHE=$(npm config get cache)
	if ! mountpoint $NPM_CACHE; then
		echo "---> Cleaning the npm cache $NPM_CACHE"
		#As of npm@5 even the 'npm cache clean --force' does not fully remove the cache directory
		rm $NPM_CACHE* -rf
	fi
	NPM_TMP=$(npm config get tmp)
	if ! mountpoint $NPM_TMP; then
		echo "---> Cleaning the $NPM_TMP/npm-*"
		rm -rf $NPM_TMP/npm-*
	fi
```

...and here is the config.json (relevant portions), which works (somewhat) with babel:

```
  "scripts": {
    "start": "node dist/index.js",
    "build": "babel lib --out-dir dist",
    "prepare": "npm run build",
    "lint": "eslint . --ignore-path .gitignore",
    "coverage": "nyc --require babel-core/register _mocha -- 'test/*.test.js'",
    "report": "nyc report --reporter=text-lcov | coveralls",
    "test": "npm run lint && npm run coverage"
  },
  // ...
  "dependencies": {
    "check-env": "1.3.0",
    "commander": "2.20.0",
    "discord.js": "11.5.1",
    "irc-colors": "1.5.0",
    "irc-formatting": "1.0.0-rc3",
    "irc-upd": "0.10.0",
    "lodash": "^4.17.15",
    "simple-markdown": "0.4.4",
    "strip-json-comments": "3.0.1",
    "winston": "3.2.1"
  },
  "devDependencies": {
    "@babel/cli": "^7.5.5",
    "@babel/core": "^7.5.5",
	"@babel/preset-env": "7.5.5",
	"babel-eslint": "^10.0.2",
    "chai": "^4.2.0",
    "coveralls": "^3.0.4",
    "eslint": "^5.16.0",
    "eslint-config-airbnb-base": "^13.2.0",
    "eslint-plugin-import": "^2.18.2",
    "mocha": "^6.1.4",
    "nyc": "^14.1.1",
    "sinon": "^7.4.1",
    "sinon-chai": "^3.3.0"
  },
  "babel": {
    "presets": [
        "@babel/preset-env"
    ]
  },
  "eslintConfig": {
    "@babel/preset-env": {
        "browser": true,
        "node": true
    }
  }
```

The ".." syntax error seems to go away with this configuration, to be replaced by this one:

```
TypeError: Cannot create property 'encoding' on string '[object Object][object Object]'
    at Bot.connect (/opt/app-root/src/dist/bot.js:164:31)
    at Object.createBots (/opt/app-root/src/dist/helpers.js:36:9)
    at Object.run [as default] (/opt/app-root/src/dist/cli.js:63:11)
    at Object.<anonymous> (/opt/app-root/src/dist/index.js:12:27)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
npm info lifecycle discord-irc@2.7.2~start: Failed to exec start script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discord-irc@2.7.2 start: `node dist/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the discord-irc@2.7.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm timing npm Completed in 860ms
```

**Comment by Throne3d** [comment] 2019-08-12 02:44
I don't have any `~/.babelrc` or `~/.eslintrc`, here, I'm on a fresh device. I don't have babel installed by anything except for `npm`, locally, to the `discord-irc` folder.

Given your question, though, I decided to test something: I deleted the `.babelrc` and `.eslintrc` that are present in the Git repo, and it gave me the error you originally encountered:

```
SyntaxError: lib/bot.js: Unexpected token (118:6)
  116 |       autoRenick: true,
  117 |       // options specified in the configuration file override the above defaults
> 118 |       ...this.ircOptions
      |       ^
  119 |     };
  120 |
  121 |     // default encoding to UTF-8 so messages to Discord aren't corrupted
```

Are you sure you've checked out the Git repo correctly? If so, did you forget to copy some files across to your container? It sure seems so.

**Comment by loopyd** [comment] 2019-08-12 02:52
Missed those files in the repo matter of fact, I'll give it a shot.

**Comment by loopyd** [comment] 2019-08-12 03:44
I'm back to the same error I expressed in the post above:

```
TypeError: Cannot create property 'encoding' on string '[object Object][object Object]'
```

After reverting the changes back in package.json to those in this repository.  I verified that my copy matches exactly, aside my config.json.

**Comment by Throne3d** [comment] 2019-08-12 04:00
What's in your config.json? (Making sure not to show your discord token.) I'm guessing this error corresponds to trying to set the `encoding` property of the `ircOptions` object, but I also can't be sure as I can't see what line the error corresponds to in the lib/bot.js file (transpiring changes the line numbers).

**Comment by loopyd** [comment] 2019-08-12 04:50
I figured it out.  It was the way that I was starting up my pod in ``s2i/bin/run`` , it works now.  After I recieved a successful build, this edit to ``s2i/bin/run`` worked out and I've got a deployment with a pod running.

Though I've run into a different issue.  IRC -> Discord is working but Discord -> IRC is nto currently, so I'm looking into resolving that one now.

````
# Runs the nodejs application server. If the container is run in development mode,
# hot deploy and debugging are enabled.
run_node() {
  echo -e "Environment: \n\tDEV_MODE=${DEV_MODE}\n\tNODE_ENV=${NODE_ENV}\n\tDEBUG_PORT=${DEBUG_PORT}"
  if [ "$DEV_MODE" == true ]; then
    echo "Launching via nodemon..."
    exec nodemon --inspect="$DEBUG_PORT"
  else
    echo "Launching via npm..."
    exec npm run -d $NPM_RUN -- --config /opt/app-root/src/config.json
  fi
} 
```

**Comment by loopyd** [comment] 2019-08-12 06:47
Fixed the other side of the relay.  Everything works in OpenShift with Source-To-Image over here.

Here's the config.json, free of tokens + ids

```
{
	"nickname": "YourBot",
	"server": "irc.yournetwork.org",
	"discordToken": "YourToken",
	"autoSendCommands": [
		["PRIVMSG", "NickServ", "IDENTIFY [YourPassword]"],
		["MODE", "YourBot", "+wixB"]
	],
	"channelMapping": {
		"[discord channel id here]": "[irc channel name] [irc password]"
	},
	"ircOptions": {
		"floodProtection": false,
		"port": "6667",
		"secure": false,
		"sasl": false
	},
	"format": {
		"commandPrelude": "Command sent by {$nickname}",
		"ircText": "<{$displayUsername}> {$text}",
		"urlAttachment": "<{$displayUsername}> [ATTCH] {$attachmentURL}",
		"discord": "**<{$author}>** {$withMentions}"
	},
	"ircNickColor": false,
	"ircPreventMention": false,
	"commandCharacters": ["!", "."],
	"ircStatusNotices": true
}
```

Hopefully this information does assist someone.  I have this + TediCross, and its super nice to consolidate a community, giving people options on platform.  Telegram <-> Discord <-> IRC in container pods.

**Comment by Throne3d** [comment] 2019-08-12 12:56
I'm glad you got it working! I can't tell what was going on before or what parts of this are necessary, so unfortunately this is probably going to remain confusing for the next person who stumbled across it, but I'm glad it's fixed.

Since I'm pretty sure the original issue here is due to an outdated node version (the one back in the original post), and this separate later issue was fixed, I'm going to close this. Feel free to get in touch if issues persist!

**Closed by Throne3d** 2019-08-12 12:56 UTC
Labels: needs info
