### ISSUE TITLE
IRC connection management

### ISSUE THREAD

**Issue by altyr** [reactiflux/discord-irc#181] opened 2017-01-18 23:01 UTC
This might not be an issue with discord-irc itself, but it's where i saw it. Console output while the bot is running below. This problem is a bit peculiar as the bot shouldn't ever have to reconnect to IRC in this instance. The number of discord reconnects seems kind of high to me, but i don't have any reference value for those (the following logs are for a roughly three day long run).

1. The IRC-Server runs on the same machine/environment as the discord-irc bot.
2. No clients other than this bot disconnected in this period of time, most of them are connected from IRCCloud.

Output from the bot:
```
runner@cortex:/srv/discord-irc$ npm start -- --config ../discord-irc.conf

> discord-irc@2.1.7 start /srv/discord-irc
> node dist/index.js "--config" "../discord-irc.conf"

info: Connected to Discord
info: Connected to IRC
info: Connected to Discord
info: Connected to Discord
info: Connected to IRC
info: Connected to Discord
info: Connected to Discord
info: Connected to Discord
(node:4618) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
(node:4618) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
info: Connected to IRC
info: Connected to Discord
info: Connected to Discord
info: Connected to Discord
info: Connected to Discord
info: Connected to Discord
info: Connected to Discord
info: Connected to Discord
info: Connected to Discord
info: Connected to Discord
info: Connected to Discord
info: Connected to Discord
info: Connected to Discord
/srv/discord-irc/node_modules/irc/lib/irc.js:936
    if (!this.conn.requestedDisconnect) {
                  ^

TypeError: Cannot read property 'requestedDisconnect' of null
    at Client.send (/srv/discord-irc/node_modules/irc/lib/irc.js:936:19)
    at Timeout.dequeue [as _onTimeout] (/srv/discord-irc/node_modules/irc/lib/irc.js:966:22)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start" "--" "--config" "../discord-irc.conf"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! discord-irc@2.1.7 start: `node dist/index.js "--config" "../discord-irc.conf"`
npm ERR! Exit status 1

--- CUT LOTS OF COMPLAINING ABOUT BEING UNABLE TO WRITE LOGFILE ---
```

Opers channel on the server (no lines removed, only changed hostnames/ips):
```
00:00:00	<─>	Sunday (January 15, 2 days later)
11:20:58	<irc.abc.xyz>	CONNECT: Client connecting on port 6697 (class local): b!b@abc.xyz(123.123.123.123) [b]
00:00:00	<─>	Tuesday (January 17, 2 days later)
05:13:42	<irc.abc.xyz>	CONNECT: Client connecting on port 6697 (class local): b!b@abc.xyz(123.123.123.123) [b]
00:00:00	<─>	Wednesday (January 18)
23:34:07	<irc.abc.xyz>	CONNECT: Client connecting on port 6697 (class local): b!b@abc.xyz(123.123.123.123) [b]
```

In any case, thanks to the team for the continued support!

**Comment by vheuken** [comment] 2017-02-05 20:47
I encountered the same errors. My bot stayed logged into IRC, but didn't post Discord messages to IRC It continued to post IRC messages to Discord, though

```
vincent@rateless:~$ discord-irc --config discord-irc-config.json
info: Connected to Discord
info: Connected to IRC
dinfo: Connected to Discord
info: Connected to Discord
info: Connected to Discord
info: Connected to Discord
info: Connected to Discord
info: Connected to Discord
info: Connected to Discord
(node:30127) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Forbidden
info: Connected to Discord
info: Connected to Discord
info: Connected to Discord
info: Connected to Discord
info: Connected to Discord
info: Connected to Discord
(node:30127) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Internal Server Error
(node:30127) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Internal Server Error
```

**Comment by OfotViking** [comment] 2017-02-10 13:25
Experienced this twice.
IRC -> Discord worked
Discord -> IRC did not work

my IRC server (Debian 7 ircd-hybrid (1:7.2.2.dfsg.2-10+deb7u1) is not on the same host as discord-irc, but the network between should be stable. Can't reproduce by interrupting the connection. 

Console output
```
$ cd ~/node_modules/discord-irc; npm start -- --config ~/config.json

> discord-irc@2.1.7 start /home/discordbot/node_modules/discord-irc
> node dist/index.js "--config" "/home/discordbot/config.json"

info: Connected to Discord
info: Connected to IRC
```
Turned on debug log in case it happens again

**Comment by gdude2002** [comment] 2017-04-02 14:46
Might be related to my new ticket, #210 - the opers on the IRC net that happened on stated that frequent reconnections is a common problem with Node bots using the `irc` module

**Comment by JJ173** [comment] 2017-04-04 17:20
Having the same issue. Currently trying to figure it out but no luck yet. If I find a work around; I'll post it here.

**Comment by JJ173** [comment] 2017-04-10 14:04
Bump?

**Comment by Throne3d** [comment] 2017-07-03 21:41
For the original issue report here, the `requestedDisconnect` issue should be fixed now, but that was a problem with the upstream IRC library, and occurred when the connection between the bot and the server is interrupted. The reconnecting with Discord would appear to indicate that it was a problem with your internet connection, in the original instance, as both the IRC and Discord sides of the bot were having trouble?

I'm not sure why you would be frequently disconnected from the Discord side of things and not the IRC side, but it could be a problem with the upstream `discord.js` library, or another internet connectivity issue.

I have noted that sometimes the bot disconnects from one side, most typically with Discord → IRC mirroring functioning but IRC → Discord not, and if I recall correctly the bot shows as offline. I'm not sure why this is and haven't managed to reproduce it on a device I'm able to debug, though.

**Comment by Throne3d** [comment] 2017-07-29 17:16
All issues but the repeated Discord connection should now be fixed. Is that issue still present? I haven't managed to reproduce it and I expect it would be a problem with the upstream `discord.js` library, like I said in the last message.

**Comment by Throne3d** [comment] 2017-09-18 00:48
(Closing for inactivity. If the issue persists, please comment in response to this with more information to have it reopened.)

**Closed by Throne3d** 2017-09-18 00:48 UTC
Labels: needs info
