### ISSUE TITLE
Discord IRC bridge suddenly stopped sending messages to Discord

### ISSUE THREAD

**Issue by ask-compu** [reactiflux/discord-irc#112] opened 2016-09-10 22:11 UTC
The bot suddenly stopped sending IRC messages to discord but it's still sending discord messages to IRC, I have no idea what is going on

**Comment by mattburchett** [comment] 2016-09-10 22:13
My fix to that was to update discord-irc to the latest version. 

`npm install -g discord-irc`

**Comment by ask-compu** [comment] 2016-09-10 22:16
that did not fix it

**Comment by ask-compu** [comment] 2016-09-10 22:17
tho i did get a new message in the terminal
http://i.imgur.com/q5YwXvg.png

**Comment by ask-compu** [comment] 2016-09-10 22:27
i even tried reauthorizing it https://github.com/reactiflux/discord-irc/wiki/Creating-a-discord-bot-&-getting-a-token by doing the invite your bot to the server section there again, still not working

**Comment by ask-compu** [comment] 2016-09-10 22:29
and now it seems to not be sending messages in any direction and is showing as offline on discord

**Comment by mattburchett** [comment] 2016-09-10 22:40
That's odd. All I had to do was update and restart the service (but my version of discord-irc was from mid-August and I assumed there was a API change or something on Discord's end.)

I just thought I'd mention my fix as I was experiencing the same issue yesterday.

Unfortunately, I don't know the app very well, so I'm not sure I can offer a better solution.

**Comment by obstriegel** [comment] 2016-09-11 04:04
Same problem here. I tried updating to the latest version but messages from IRC are not getting to Discord anymore.

> discord-irc@1.0.3 start [some path here]
> node dist/index.js "--config" "config.json"

@ask-compu The "new" message you suggested is not related to this issue I think. You also get it when the bot is not in the Discord channel in previous versions.

**Comment by ask-compu** [comment] 2016-09-11 04:05
@obstriegel so what do i do?

**Comment by obstriegel** [comment] 2016-09-11 04:42
@ask-compu well... The discord package changed. So just run
> npm install
in the directory where you have installed the bridge. Maybe you have not installed the stuff globally like me so if you have a "node_modules" directory there it should update it (It contains the discord.js file which needs to get updated).

It is definitely not a bug of this package so this issue can be closed.

**Comment by ask-compu** [comment] 2016-09-11 04:45
@obstriegel im not sure how it isnt is there something wrong with npm? i did npm install -g discord-irc but it said it couldnt write to the directories it needed so i did the same command but with sudo and it worked, if -g installs globally then i definitely installed it globally

**Comment by obstriegel** [comment] 2016-09-11 04:57
@ask-compu if you do "find ~ -name discord.js" maybe you see it in your home directory in .npm .
I think it uses this local version before searching in global scope where you install it with -g and of course root privileges.

**Comment by ask-compu** [comment] 2016-09-11 05:39
i have a discord.js in the .npm folder in my home directory but not one in the node_modules directory

**Comment by ask-compu** [comment] 2016-09-11 05:41
but just in case i did npm uninstall discord-irc and sudo npm uninstall -g discord-irc and now will do sudo npm install -g discord-irc

**Comment by ask-compu** [comment] 2016-09-11 05:43
that didnt work, the install worked but im still getting the http://i.imgur.com/q5YwXvg.png message and its still not forwarding any messages in either direction and is still showing as offline in discord

**Comment by hewball** [comment] 2016-09-11 07:36
im still getting 1 way chat discord to irc but not irc to discord, latest update installed

**Comment by Akkadius** [comment] 2016-09-11 20:54
Can confirm 1-way communication as well - no IRC to discord

**Comment by Akkadius** [comment] 2016-09-12 05:00
Looks like there can be an issue with npm updating globally when you use the -g flag.

You can build locally to another folder via npm install discord-irc, you'll see it build here from the point where you ran the command:

/node_modules/.bin/discord-irc

Run 'discord-irc version' and it will report the version, if it's 1.0.3 it has the updated discord.js and you will get your two-way communication back.

You're welcome

**Comment by ask-compu** [comment] 2016-09-12 05:24
@Akkadius doing discord-irc --version (the global discord-irc i have installed) reports 1.0.3, still having the issue tho

**Comment by vikbez** [comment] 2016-09-12 08:23
Maybe related to https://github.com/hydrabolt/discord.js/issues/683 ?

**Comment by FrostTheFox** [comment] 2016-09-13 01:37
I'm having a similar issue, except mine is with messages coming into IRC from Discord. IRC messages go across fine to Discord. It seems to work at certain times, then at others simply stops.

**Comment by billimek** [comment] 2016-09-13 13:02
Not sure if this will help anyone, but I use a fork of discord-irc and was able to get the IRC->Discord functionality to work with the changes in this commit on my fork: https://github.com/billimek/discord-irc/commit/a488e2f15da8ea63f3e763800a7790284f427509

**Comment by zed0** [comment] 2016-09-13 13:39
This problem is due to an update to the Discord API: https://github.com/hammerandchisel/discord-api-docs/issues/119
A work around for this problem is to change your config file and prepend `'Bot '` to the start of your `discordToken` line, e.g.
From `"discordToken": "mysupersecrettoken",`
To `"discordToken": "Bot mysupersecrettoken",`

**Comment by atc3030** [comment] 2016-09-13 13:52
Can confirm that zed0's suggestion solved my issue where I had Discord to IRC but not IRC to Discord. Thanks!

**Comment by ask-compu** [comment] 2016-09-13 13:52
@zed0 seems to have no effect on my issue, still getting http://i.imgur.com/q5YwXvg.png and no forwarding in either direction

**Comment by Demorde** [comment] 2016-09-14 02:12
I am having the opposite issue with this - Discord > IRC isn't working, IRC > Discord works fine.

**Comment by ekmartin** [comment] 2016-09-14 03:30
@zed0 @atc3030, that's exactly what version 1.0.3 of discord-irc introduces, by using the `indev-old` version of discord-js (which prefixes tokens with `Bot`).

**Comment by smashedr** [comment] 2016-09-14 05:06
Since upgrading to 1.0.3 I get the same error:

`Tried to send a message to a channel the bot isn't in`

But it also seems the bot is not even online in Discord.

**Comment by ask-compu** [comment] 2016-09-14 10:43
@ekmartin is there a debug flag or something that will make discord-irc give more detailed error messages and such? the bot isn't in the channel can mean anything from the bot not being able to access the api to the bot getting an error message

**Comment by FrostTheFox** [comment] 2016-09-16 01:39
Can we get an update on this? I'm still experiencing the issue with Discord ---> IRC not working on restart, it takes hours before it eventually works. I've tried multiple install methods, multiple reinstalls, reinstalling the dependencies, etc, still having the same issue.

**Comment by FrostTheFox** [comment] 2016-09-17 05:42
Also would like to mention that I'm not seeing any sort of indication of error. It just wont work for a certain period of time, then magically starts working.

**Comment by ask-compu** [comment] 2016-09-17 15:16
well it's been a week and we've gotten no real response the devs will fix this, i'm not sure it's going to be fixed

**Comment by FrostTheFox** [comment] 2016-09-17 21:02
@ask-compu which is quite annoying because I started my IRC with the express purpose of having two channels linked to the discord :/

**Comment by ask-compu** [comment] 2016-09-19 23:27
@FrostTheFox im starting to wonder if the devs r still actively developing this

**Comment by ekmartin** [comment] 2016-09-19 23:38
The "devs" you're referring to is in its entirety, in exception to a few cool contributions, solely me. I don't have time to work on this at the moment, as believe it or not, developing discord-irc isn't my full-time job. I'm sure you've noticed, but this project is open source - and if you were to read the [license](https://github.com/reactiflux/discord-irc/blob/master/LICENSE) it's provided under I'm positive it would give you some kind of hint of what that means.

**Comment by smashedr** [comment] 2016-09-20 04:20
So from what I can tell discord-irc is working fine and this is just a duplicate of #73 

Something did change about a week ago and this now requires node 6 or greater; so maybe the requirements should be updated as a result of this Issue.
https://github.com/reactiflux/discord-irc/blob/master/package.json#L14

If you uninstall discord-irc, uninstall nodejs, install nodejs >=6, install discord-irc, this program should begin working instantly as expected. If you are using node >6, try downgrading to 6.

Note: I am running this as a systemd service with `Restart=always`

```
# cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
# node --version
v6.6.0
# discord-irc --version
1.0.3
```

Hope this helps, I will update the thread if anything changes, or I notice any unexpected behavior.

**Comment by FrostTheFox** [comment] 2016-09-20 04:33
@Akkadius I run a large open source project myself and I understand what goes into fixing these bugs. I am also quite aware what is entitlement looks like as I deal with it on a daily basis. I have simply been asking for an update because I would like to know if there's some sort of way I can assist in finding the cause of this. As for others, I could possibly see what you mean.

@smashedr for me it's not quite a duplicate of that issue, it works completely fine after a couple hours, but it seems to have some sort of trouble sending discord messages to IRC initially. Can't find anything wrong on the IRC side of things,

**Comment by FrostTheFox** [comment] 2016-09-20 04:36
@Akkadius Also, telling others to "fix it themselves" shouldn't be an attitude when you're dealing with people who aren't on a level of programming near you. It's good that you've written yourself a workaround, but not everyone knows how to do that.

**Comment by smashedr** [comment] 2016-09-20 04:40
@FrostTheFox I think the issue you are experiencing may be isolated to your IRC server as I run many instances of discord-irc and do not have that issue.

You can enable debugging on the IRC side of things. It uses `node-irc` so try setting `debug: true` in the `config.json`.

There are some additional retry options you can set, you can find more about `node-irc` here:
http://node-irc.readthedocs.io/en/latest/API.html

**Comment by FrostTheFox** [comment] 2016-09-20 04:41
@smashedr I have tried moving to other IRC servers running various softwares and am still experiencing a similar issue, but I will take a look at the node-irc debug a little further.

**Comment by ask-compu** [comment] 2016-09-20 12:54
@smashedr upgrading my node version seems to have solved my problem

**Comment by ask-compu** [comment] 2016-09-20 12:56
@FrostTheFox have ur bot connect to #Compu on irc.canternet.org and see if the issue happens there, thats where im using the bot, it's my channel so u have my permission to do this as a test

**Comment by ekmartin** [comment] 2016-09-21 01:52
Everything discord-irc does regarding Discord happens through [discord.js](https://github.com/hydrabolt/discord.js). discord-irc currently a slightly older version of discord.js, but with an added patch that were supposed to fix the Discord API changes.

I've been hesitant towards upgrading to discord.js v9, as it requires Node 6 or newer - while I'd rather support at least the current LTS version (which at the moment is 4). Seeing as there's different connectivity issues than what was fixed in the patched version of discord.js v8, I think it's worth giving it a shot though, as version 9 is supposed to be quite a substantial rewrite.

If someone's interested in sending a pull request that upgrades discord-irc's discord.js version to the latest, that would be greatly appreciated. Not sure how much breaking changes there are, as their changelog isn't up to date, however there's an upgrade guide [here](https://yorkaargh.wordpress.com/2016/09/03/updating-discord-js-bots/), with docs [here](http://hydrabolt.github.io/discord.js/#!/docs/tag/master/file/general/Welcome).

**Comment by ekmartin** [comment] 2016-09-26 01:25
I've upgraded our discord.js version to v9.3 (apparently a significant rewrite), which hopefully should fix this. As mentioned above discord.js v9 requires Node.js 6+, which means that discord-irc now does the same. I've released this as version 2 of discord-irc, since it's a breaking change. Give it a try, and let me know if the issue still persists and I'll reopen.

**Closed by ekmartin** 2016-09-26 01:25 UTC
