### ISSUE TITLE
Bot randomly disconnects from Discord and doesn't reconnect.

### ISSUE THREAD

**Issue by deathspawn** [reactiflux/discord-irc#159] opened 2016-11-20 23:20 UTC
I'm not sure why it disconnects as there are no logs. The only way I can get it to reconnect is to restart the bot. It will remain on IRC and somehow still relay messages from IRC to Discord. On the Discord side, it shows up as offline and relays nothing from Discord to IRC.

**Comment by StrikerMan780** [comment] 2016-11-23 00:52
I can confirm. Restarting the bot will usually make it connect again, but it's still not perfect.

**Comment by pseiler** [comment] 2016-12-02 09:13
I can confirm it too.

**Comment by jamesguessis** [comment] 2016-12-02 16:00
Happens to me too often ;-;

**Comment by Paril** [comment] 2016-12-06 22:21
Happens here as well.

**Comment by ekmartin** [comment] 2016-12-09 04:37
discord-irc doesn't really handle the connection to Discord, it uses discord.js for that (which also is supposed to support reconnecting upon disconnects).

There was a recent reconnect pull request though, which hasn't been released yet: https://github.com/hydrabolt/discord.js/pull/952
I'll update discord-irc to the latest version as soon as it releases. 

In the meantime I've added loggers for the `warn` and `debug` Discord events, to help debug why it disconnects. This is released in version [2.1.6](https://github.com/reactiflux/discord-irc/blob/master/CHANGELOG.md#216---2016-12-08) of discord-irc. `debug` events are only enabled in development, which is signified by setting the environment variable `NODE_ENV` to `development`. Example: `NODE_ENV=development discord-irc --config config.json`.

**Comment by altyr** [comment] 2016-12-14 18:50
Looks like the bug is still present in discord.js, multiple bot devs have reported problems with their bots not always reconnecting to discord. See  hydrabolt/discord.js#965

**Comment by altyr** [comment] 2017-01-06 19:43
Discord.js 11 is out.
Unfortunately it seems to introduce some breaking changes:

```
/srv/discord-irc/node_modules/discord.js/src/util/Collection.js:151
      if (propOrFn === 'id') throw new RangeError('Don\'t use .find() with IDs. Instead, use .get(id).');
                             ^

RangeError: Don't use .find() with IDs. Instead, use .get(id).
    at Collection.find (/srv/discord-irc/node_modules/discord.js/src/util/Collection.js:151:36)
    at Function.getDiscordNicknameOnServer (/srv/discord-irc/dist/bot.js:133:39)
    at Bot.sendToIRC (/srv/discord-irc/dist/bot.js:167:28)
    at Client.discord.on.message (/srv/discord-irc/dist/bot.js:108:12)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at MessageCreateHandler.handle (/srv/discord-irc/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/srv/discord-irc/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:120:65)
    at WebSocketManager.eventMessage (/srv/discord-irc/node_modules/discord.js/src/client/websocket/WebSocketManager.js:273:31)
    at WebSocketClient.internalOnMessage (/srv/discord-irc/node_modules/uws/uws.js:89:17)
```

**Comment by ekmartin** [comment] 2017-01-10 21:25
@altyr I fixed the breaking changes and released a new version (2.1.7). Feel free to give it a try.

**Comment by ekmartin** [comment] 2017-01-10 21:25
I'm gonna try closing this, since discord.js closed the upstream issue as fixed. Let me know if it still persists with 2.1.7 and I'll reopen.

**Closed by ekmartin** 2017-01-10 21:25 UTC
Labels: upstream bug

**Comment by StrikerMan780** [comment] 2017-01-12 02:05
Gonna put it on NPM?

**Comment by ekmartin** [comment] 2017-01-12 03:34
@StrikerMan780 2.1.7 should be on npm. Did you manage to install it?

**Comment by StrikerMan780** [comment] 2017-01-12 08:39
Got it sorted out. Made a note on the bottom of my last post.

**Comment by StrikerMan780** [comment] 2017-02-04 00:50
Even though I upgraded my copy of Discord.js and Discord-irc, I still get random disconnects.

**Comment by overfl0** [comment] 2017-02-25 13:26
I ran discord-irc with in debug mode and left it running on screen until it disconnected (usually after 3-5 days)

This is the last output lines that were on screen:
```
debug: Received debug event from Discord Heartbeat acknowledged
debug: Received debug event from Discord Sending heartbeat
debug: Received debug event from Discord Heartbeat acknowledged
debug: Received debug event from Discord Sending heartbeat
debug: Received debug event from Discord Connecting to gateway wss://gateway.discord.gg/?v=6&encoding=etf
error: Received error event from Discord
```

**Comment by chaziz94** [comment] 2021-01-09 06:25
this issue still persists more than 4 years later

**Comment by PrieurA** [comment] 2021-09-23 23:54
Experiencing the same issue 24 September 2021 🙃

**Comment by ic-08** [comment] 2021-12-27 21:08
Still have the same problem
I'm not sure about discord.js but this issue is the same on discord.py too
It's almost 2022🤣

**Comment by HexiDev** [comment] 2023-09-20 08:07
Still a issue...

**Comment by pseiler** [comment] 2023-09-20 16:01
project seems dead. But I do not have issuess like this with projects using discord.py
